# Generated by Django 4.0.3 on 2022-06-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('memberCount', models.IntegerField(default=0)),
                ('startDay', models.DateField(default=0)),
                ('finishDay', models.DateField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedTime', models.DateTimeField(auto_now=True, null=True)),
                ('groupPic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('joinedUser', models.ManyToManyField(blank=True, related_name='group_joined_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
