# Generated by Django 4.0.3 on 2022-06-17 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='group_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
