# Generated by Django 4.0.3 on 2022-06-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('count', models.IntegerField(blank=True)),
                ('set', models.IntegerField(blank=True)),
                ('bodyPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_body_part', to='exercise.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_session_session', to='exercise.session')),
            ],
        ),
    ]
