# Generated by Django 4.0.3 on 2022-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendsession",
            name="session",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommend_session_session",
                to="exercise.session",
            ),
        ),
    ]
