# Generated by Django 4.0.3 on 2022-06-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='imageUrl',
        ),
    ]
