# Generated by Django 4.0.3 on 2022-06-16 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100)),
                ('sessions', models.TextField(blank=True, max_length=1000)),
                ('duration', models.TextField(blank=True, max_length=1000)),
                ('createdTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedTime', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
