# Generated by Django 4.0.3 on 2022-06-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_duration_record_bodyparts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='durations',
            new_name='eachTimes',
        ),
    ]
